spring.application.name=eventos-reservas
server.port=8080

# Usar H2 en lugar de MySQL para evitar errores de conexión
spring.datasource.url=jdbc:h2:mem:bdduser;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.datasource.url=jdbc:h2:mem:bdduser;NON_KEYWORDS=USER

# Crear tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

# JWT Config (Secret de 64 caracteres)
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# Swagger Config
springdoc.swagger-ui.path=/swagger-ui/index.html